development:
  adapter: redis
  url: <%= Rails.application.secrets.redis[:url] %>
  channel_prefix: psm_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.secrets.redis[:url] %>
  channel_prefix: psm_production
