name: Sync to Upstream

on:
  schedule:
    - cron:  '0 0 * * *'
    # scheduled at every day
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Pull upstream changes
        id: sync
        uses: bdougie/Fork-Sync-With-Upstream-action@fork
        with:
          upstream_repository: personal-social-media/personal-social-media
          upstream_branch: master
          target_branch: production
